"""
Parse Arsenbo catalogue2026.pdf — extract text per page and embed images.
Outputs:
  - D:/fridge/public/catalog/arsenbo/    → extracted images
  - D:/fridge/src/data/catalog-pages.ts  → structured page data for the website
"""
import fitz  # PyMuPDF
import json
import os
import hashlib
from pathlib import Path

PDF_PATH = r"C:\Users\luckywu\Desktop\Arsenbo catalogue2026.pdf"
OUTPUT_IMG_DIR = Path(r"D:\fridge\public\catalog\arsenbo")
OUTPUT_DATA_FILE = Path(r"D:\fridge\src\data\catalog-pages.ts")

# Create output directories
OUTPUT_IMG_DIR.mkdir(parents=True, exist_ok=True)

doc = fitz.open(PDF_PATH)
total_pages = len(doc)
print(f"PDF opened: {total_pages} pages")

catalog_pages = []

for page_num in range(total_pages):
    page = doc[page_num]
    text = page.get_text("text").strip()
    
    # Extract images from this page
    images_on_page = []
    image_list = page.get_images(full=True)
    
    for img_idx, img in enumerate(image_list):
        xref = img[0]
        base_image = doc.extract_image(xref)
        image_bytes = base_image["image"]
        image_ext = base_image["ext"]  # png, jpeg, etc.
        
        # Generate unique filename based on content hash
        img_hash = hashlib.md5(image_bytes).hexdigest()[:8]
        img_filename = f"page{page_num+1:02d}_img{img_idx+1:02d}_{img_hash}.{image_ext}"
        img_path = OUTPUT_IMG_DIR / img_filename
        
        # Save image
        with open(img_path, "wb") as f:
            f.write(image_bytes)
        
        img_size_kb = len(image_bytes) / 1024
        images_on_page.append({
            "filename": img_filename,
            "ext": image_ext,
            "sizeKb": round(img_size_kb, 1),
            "pageNum": page_num + 1,
            "index": img_idx + 1,
        })
    
    # Determine page type based on content
    text_lower = text.lower()
    page_type = "general"
    if "specif" in text_lower or "technical" in text_lower or "parameter" in text_lower:
        page_type = "specs"
    elif "feature" in text_lower or "advantage" in text_lower or "benefit" in text_lower:
        page_type = "features"
    elif "application" in text_lower or "industry" in text_lower or "case" in text_lower:
        page_type = "applications"
    elif "certif" in text_lower or "compliance" in text_lower or "standard" in text_lower:
        page_type = "certifications"
    
    catalog_pages.append({
        "pageNumber": page_num + 1,
        "pageType": page_type,
        "textContent": text[:3000],  # Truncate very long pages
        "textLength": len(text),
        "images": images_on_page,
    })
    
    if images_on_page:
        print(f"Page {page_num+1}: {len(text)} chars, {len(images_on_page)} images extracted")
    else:
        print(f"Page {page_num+1}: {len(text)} chars, no images")

doc.close()

# Write TypeScript data file
ts_lines = [
    "// Auto-generated from Arsenbo catalogue2026.pdf",
    "// DO NOT EDIT MANUALLY — regenerated by parse-catalog.py",
    "",
    "export interface CatalogImage {",
    "  filename: string;",
    "  ext: string;",
    "  sizeKb: number;",
    "  pageNum: number;",
    "  index: number;",
    "}",
    "",
    "export interface CatalogPage {",
    "  pageNumber: number;",
    "  pageType: string;",
    "  textContent: string;",
    "  textLength: number;",
    "  images: CatalogImage[];",
    "}",
    "",
    f"export const catalogPages: CatalogPage[] = {json.dumps(catalog_pages, ensure_ascii=False, indent=2)};",
    "",
]

with open(OUTPUT_DATA_FILE, "w", encoding="utf-8") as f:
    f.write("\n".join(ts_lines))

# Summary
total_images = sum(len(p["images"]) for p in catalog_pages)
total_text = sum(p["textLength"] for p in catalog_pages)
print(f"\n--- SUMMARY ---")
print(f"Total pages: {total_pages}")
print(f"Total images extracted: {total_images}")
print(f"Total text chars: {total_text}")
print(f"Images saved to: {OUTPUT_IMG_DIR}")
print(f"Data file: {OUTPUT_DATA_FILE}")
