// Auto-generated from Arsenbo catalogue2026.pdf
// DO NOT EDIT MANUALLY — regenerated by parse-catalog.py

export interface CatalogImage {
  filename: string;
  ext: string;
  sizeKb: number;
  pageNum: number;
  index: number;
}

export interface CatalogPage {
  pageNumber: number;
  pageType: string;
  textContent: string;
  textLength: number;
  images: CatalogImage[];
}

export const catalogPages: CatalogPage[] = [
  {
    "pageNumber": 1,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page01_img01_f60e4fde.jpeg",
        "ext": "jpeg",
        "sizeKb": 5554.0,
        "pageNum": 1,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 2,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page02_img01_1ed91d6c.jpeg",
        "ext": "jpeg",
        "sizeKb": 409.5,
        "pageNum": 2,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 3,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page03_img01_75af3583.jpeg",
        "ext": "jpeg",
        "sizeKb": 1659.8,
        "pageNum": 3,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 4,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page04_img01_116dbda3.jpeg",
        "ext": "jpeg",
        "sizeKb": 11011.1,
        "pageNum": 4,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 5,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page05_img01_548959a2.jpeg",
        "ext": "jpeg",
        "sizeKb": 1713.1,
        "pageNum": 5,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 6,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page06_img01_1910e115.jpeg",
        "ext": "jpeg",
        "sizeKb": 1803.1,
        "pageNum": 6,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 7,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page07_img01_8aa32fcf.jpeg",
        "ext": "jpeg",
        "sizeKb": 1137.0,
        "pageNum": 7,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 8,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page08_img01_ab269a0c.jpeg",
        "ext": "jpeg",
        "sizeKb": 1914.9,
        "pageNum": 8,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 9,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page09_img01_e4867f5d.jpeg",
        "ext": "jpeg",
        "sizeKb": 2061.4,
        "pageNum": 9,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 10,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page10_img01_da5f38a8.jpeg",
        "ext": "jpeg",
        "sizeKb": 1503.9,
        "pageNum": 10,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 11,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page11_img01_edb8439c.jpeg",
        "ext": "jpeg",
        "sizeKb": 1582.8,
        "pageNum": 11,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 12,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page12_img01_b4819e5f.jpeg",
        "ext": "jpeg",
        "sizeKb": 1772.2,
        "pageNum": 12,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 13,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page13_img01_ff17cf7a.jpeg",
        "ext": "jpeg",
        "sizeKb": 1810.9,
        "pageNum": 13,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 14,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page14_img01_d95b8273.jpeg",
        "ext": "jpeg",
        "sizeKb": 1772.6,
        "pageNum": 14,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 15,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page15_img01_143a941e.jpeg",
        "ext": "jpeg",
        "sizeKb": 1799.0,
        "pageNum": 15,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 16,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page16_img01_45e33112.jpeg",
        "ext": "jpeg",
        "sizeKb": 1725.1,
        "pageNum": 16,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 17,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page17_img01_c18a195c.jpeg",
        "ext": "jpeg",
        "sizeKb": 1849.8,
        "pageNum": 17,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 18,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page18_img01_73c6c26d.jpeg",
        "ext": "jpeg",
        "sizeKb": 1399.3,
        "pageNum": 18,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 19,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page19_img01_2993fdc3.jpeg",
        "ext": "jpeg",
        "sizeKb": 1787.2,
        "pageNum": 19,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 20,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page20_img01_9fb78f69.jpeg",
        "ext": "jpeg",
        "sizeKb": 2214.6,
        "pageNum": 20,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 21,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page21_img01_4303521a.jpeg",
        "ext": "jpeg",
        "sizeKb": 1628.9,
        "pageNum": 21,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 22,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page22_img01_dd92bab5.jpeg",
        "ext": "jpeg",
        "sizeKb": 1631.0,
        "pageNum": 22,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 23,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page23_img01_5e7cc5ea.jpeg",
        "ext": "jpeg",
        "sizeKb": 1850.7,
        "pageNum": 23,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 24,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page24_img01_f68c3435.jpeg",
        "ext": "jpeg",
        "sizeKb": 2277.5,
        "pageNum": 24,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 25,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page25_img01_ff6b0704.jpeg",
        "ext": "jpeg",
        "sizeKb": 1902.9,
        "pageNum": 25,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 26,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page26_img01_3dd8320a.jpeg",
        "ext": "jpeg",
        "sizeKb": 1817.8,
        "pageNum": 26,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 27,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page27_img01_f1e25a51.jpeg",
        "ext": "jpeg",
        "sizeKb": 1388.7,
        "pageNum": 27,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 28,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page28_img01_cdfb48b1.jpeg",
        "ext": "jpeg",
        "sizeKb": 1551.1,
        "pageNum": 28,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 29,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page29_img01_acb26984.jpeg",
        "ext": "jpeg",
        "sizeKb": 1430.1,
        "pageNum": 29,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 30,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page30_img01_c5c9f41f.jpeg",
        "ext": "jpeg",
        "sizeKb": 1474.7,
        "pageNum": 30,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 31,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page31_img01_3f757bc8.jpeg",
        "ext": "jpeg",
        "sizeKb": 1865.7,
        "pageNum": 31,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 32,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page32_img01_3a80bfef.jpeg",
        "ext": "jpeg",
        "sizeKb": 886.5,
        "pageNum": 32,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 33,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page33_img01_74aed35d.jpeg",
        "ext": "jpeg",
        "sizeKb": 1298.2,
        "pageNum": 33,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 34,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page34_img01_e9b17150.jpeg",
        "ext": "jpeg",
        "sizeKb": 1399.8,
        "pageNum": 34,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 35,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page35_img01_094f24c9.jpeg",
        "ext": "jpeg",
        "sizeKb": 1240.3,
        "pageNum": 35,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 36,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page36_img01_bc2c2858.jpeg",
        "ext": "jpeg",
        "sizeKb": 1141.3,
        "pageNum": 36,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 37,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page37_img01_0b0aa1c0.jpeg",
        "ext": "jpeg",
        "sizeKb": 1246.4,
        "pageNum": 37,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 38,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page38_img01_fc0300c3.jpeg",
        "ext": "jpeg",
        "sizeKb": 1258.1,
        "pageNum": 38,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 39,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page39_img01_607e8f98.jpeg",
        "ext": "jpeg",
        "sizeKb": 1415.0,
        "pageNum": 39,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 40,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page40_img01_bb7ddbab.jpeg",
        "ext": "jpeg",
        "sizeKb": 1466.8,
        "pageNum": 40,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 41,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page41_img01_ee5bb2f0.jpeg",
        "ext": "jpeg",
        "sizeKb": 1376.2,
        "pageNum": 41,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 42,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page42_img01_112e80f9.jpeg",
        "ext": "jpeg",
        "sizeKb": 1496.2,
        "pageNum": 42,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 43,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page43_img01_a19b8a50.jpeg",
        "ext": "jpeg",
        "sizeKb": 1155.7,
        "pageNum": 43,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 44,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page44_img01_1d88094f.jpeg",
        "ext": "jpeg",
        "sizeKb": 1444.9,
        "pageNum": 44,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 45,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page45_img01_a71b5a9d.jpeg",
        "ext": "jpeg",
        "sizeKb": 1203.3,
        "pageNum": 45,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 46,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page46_img01_5b4334be.jpeg",
        "ext": "jpeg",
        "sizeKb": 1490.7,
        "pageNum": 46,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 47,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page47_img01_296b27fc.jpeg",
        "ext": "jpeg",
        "sizeKb": 1646.6,
        "pageNum": 47,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 48,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page48_img01_0b7e047e.jpeg",
        "ext": "jpeg",
        "sizeKb": 1481.7,
        "pageNum": 48,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 49,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page49_img01_469d03ac.jpeg",
        "ext": "jpeg",
        "sizeKb": 1519.7,
        "pageNum": 49,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 50,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page50_img01_37c0e774.jpeg",
        "ext": "jpeg",
        "sizeKb": 1557.4,
        "pageNum": 50,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 51,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page51_img01_a55123a7.jpeg",
        "ext": "jpeg",
        "sizeKb": 1435.8,
        "pageNum": 51,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 52,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page52_img01_98401955.jpeg",
        "ext": "jpeg",
        "sizeKb": 2486.1,
        "pageNum": 52,
        "index": 1
      }
    ]
  },
  {
    "pageNumber": 53,
    "pageType": "general",
    "textContent": "",
    "textLength": 0,
    "images": [
      {
        "filename": "page53_img01_235c6793.jpeg",
        "ext": "jpeg",
        "sizeKb": 782.4,
        "pageNum": 53,
        "index": 1
      }
    ]
  }
];
